"""fixed Show

Revision ID: 07ad1c5fcab9
Revises: 0f852c3d8abc
Create Date: 2024-09-12 03:08:07.553219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ad1c5fcab9'
down_revision = '0f852c3d8abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
